# Site settings
title: "🌸🐳 \  HynDuf \  👋"
SEOTitle: HynDuf Blog
header-img: img/hollow-knight.png
email: miyoko076@inbox.lv
description: "May it get me? 🌸"
keyword: "hynduf, @hynduf, HynDuf's Blog, CP, Arch Linux, Obsidian"
url: "https://miyoko076.netlify.app"
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: miyoko076
# twitter_username:
# facebook_username:
# linkedin_username:

# Build settings
timezone: Asia/Seoul
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
# if you want to customize anchor. check out line:181 of `post.html`
anchorjs: true

# Gems
plugins: [jekyll-paginate]

# Markdown settings
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username:

# Netease settings
netease_comment: false

# Analytics settings
# ga_track_id: # Format: UA-xxxxxx-xx
# ga_domain:

# Sidebar settings
sidebar: true
sidebar-about-description: "how far down the <br/> rabbit holes 🐇, <br/> would it take me? 🤔"
sidebar-avatar: https://github.com/Miyoko076.png

# Featured Tags
featured-tags: true
featured-condition-size: 0

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Friends
friends:
#   [
#     { title: "Vanhger", href: "https://vanhger.github.io/" },
#   ]

